name: Docker Image CI

on:
  push:
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["7.4", "8.0"]
        # php: ["7.4", "8.0", "8.1"] # Wait for publish of the docker-image
        type: [cli, fpm, cli-node, fpm-node]

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.2
      with:
        context: php/${{ matrix.php }}/${{ matrix.type }}
        push: true
        tags: chapterjason/php:${{ matrix.php }}-${{ matrix.type }}-alpine
